### PR TITLE
add code and md linters

### PR DESCRIPTION
**Pull request by chicco785**
## Proposed changes

add code and md linters

## Types of changes

What types of changes does your code introduce to the project: _Put
an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing
      functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after
creating the PR. If you're unsure about any of them, don't hesitate to
ask. We're here to help! This is simply a reminder of what we are going
to look for before merging your code._

- [x] I have read the [CONTRIBUTING][contrib] doc
- [x] I have signed the [CLA][cla]
- [ ] I have added tests that prove my fix is effective or that my
      feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in
      downstream modules

## Further comments

N/A

[cla]: https://fiware.github.io/contribution-requirements/individual-cla.pdf
    "FIWARE Individual Contributor License Agreement"
[contrib]: https://github.com/smartsdk/ngsi-timeseries-api/blob/master/CONTRIBUTING.md
    "Contributing to QuantumLeap"

### CODE REVIEW

**Comment by c0c0n3** [comment]
nice one! but how do you run the linters locally on your box? we should probably add a section about linting to:

- https://github.com/orchestracities/ngsi-timeseries-api/wiki/Dev-Cookbook

so devs can hook up the linters in their IDEs/editors/whatever we use.

**Comment by chicco785** [comment]
> nice one! but how do you run the linters locally on your box? we should probably add a section about linting to:
> 
> * https://github.com/orchestracities/ngsi-timeseries-api/wiki/Dev-Cookbook
> 
> so devs can hook up the linters in their IDEs/editors/whatever we use. I can do that but need some input from you...

i added a script for md (no need for python, it's done by the script).
to finalise the clean up of md is quite a pain... can do today

**Comment by c0c0n3** [comment]
> to finalise the clean up of md is quite a pain... can do today

yeah, I can see that in the commits, but take it easy, no rush!

**Comment by c0c0n3** [comment]
@chicco785, during the FIWARE TSC on 15 Feb 2021 we talked about applying for GE status. We should be able to do that as soon as we merge this PR which should make us score 100% on the CII best practices questionnaire. Things to do after the merge:

1. Update CII best practices questionnaire, make sure we get a pass.
2. Review FIWARE GE requirements---I think we did this already back in the day, but we should double-check if there's anything still missing.
3. Get in touch with @jason-fox to kick off the GE application procedure.

**Pull request merged**
