### PR TITLE
test multiple version of backends

### PR DESCRIPTION
**Pull request by chicco785**
## Proposed changes

Current ci tests just the last version supported of crate and timescale.
This PR use the parameter matrix to test multiple version of the backends
only for the translator tests (this is to avoid that time generally explode).

Eventually we will add also the matrix for the integration & bc tests,
for this reason, integration tests are now split.

## Types of changes

What types of changes does your code introduce to the project: _Put
an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing
      functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after
creating the PR. If you're unsure about any of them, don't hesitate to
ask. We're here to help! This is simply a reminder of what we are going
to look for before merging your code._

- [x] I have read the [CONTRIBUTING][contrib] doc
- [x] I have signed the [CLA][cla]
- [x] I have added tests that prove my fix is effective or that my
      feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in
      downstream modules

## Further comments
N/A

[cla]: https://raw.githubusercontent.com/orchestracities/ngsi-timeseries-api/master/individual-cla.pdf
    "Martel Open Source Software Individual Contributor License Agreement"
[contrib]: https://github.com/smartsdk/ngsi-timeseries-api/blob/master/CONTRIBUTING.md
    "Contributing to QuantumLeap"

### CODE REVIEW

**Comment by chicco785** [comment]
while the tests runs well, coveralls is not reporting... maybe timeout?

**Comment by chicco785** [comment]
> while the tests runs well, coveralls is not reporting... maybe timeout?

so it only takes a lot of time

**Comment by chicco785** [comment]
weird enough, by combining multiple test versions in the integration step, coverage decrease...

**Review by c0c0n3 — APPROVED** [review]
awesome sauce!!!

**Comment by c0c0n3** [comment]
> coverage/coveralls — Coverage remained the same at 4.96%

it looks like the coverage file produced by pytest doesn't get picked up. not sure why that is. or could it be something overrides it and we wind up w/ an empty file?

**Comment by chicco785** [comment]
> > coverage/coveralls — Coverage remained the same at 4.96%
> 
> it looks like the coverage file produced by pytest doesn't get picked up. not sure why that is. or could it be something overrides it and we wind up w/ an empty file?

i think the problem is that the all thing takes too much time and coveralls does not like it...

**Comment by c0c0n3** [comment]
but doesn't this

https://github.com/orchestracities/ngsi-timeseries-api/pull/492/files#diff-78a8a19706dbd2a4425dd72bdab0502ed7a2cef16365ab7030a5a0588927bf47R136

run at the end of the test session? or you meant you think the command to upload the file actually takes too long? it could also be the file is too big and there's a size limit... we can try testing this locally after merging this PR to get an idea of what the issue might be...

**Comment by chicco785** [comment]
> but doesn't this
> 
> https://github.com/orchestracities/ngsi-timeseries-api/pull/492/files#diff-78a8a19706dbd2a4425dd72bdab0502ed7a2cef16365ab7030a5a0588927bf47R136
> 
> run at the end of the test session? or you meant you think the command to upload the file actually takes too long? it could also be the file is too big and there's a size limit... we can try testing this locally after merging this PR to get an idea of what the issue might be...

all files are sent at the end of each single test, then there is a final messages that says, testing session ended.

so, issues could be: to long time between start and end, or too many test outcomes files for the same test..

**Pull request merged**
