### PR TITLE
Added warning in response format 

### PR DESCRIPTION
**Pull request by daminichopra**
## Proposed changes

Added warning in response format for Fix of [Issue](https://github.com/orchestracities/ngsi-timeseries-api/issues/514)

## Types of changes

What types of changes does your code introduce to the project: _Put
an `x` in the boxes that apply_

- [ x ] Bugfix (non-breaking change which fixes an issue)
- [ x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing
      functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after
creating the PR. If you're unsure about any of them, don't hesitate to
ask. We're here to help! This is simply a reminder of what we are going
to look for before merging your code._

- [ x ] I have read the [CONTRIBUTING][contrib] doc
- [ x ] I have signed the [CLA][cla]
- [ ] I have added tests that prove my fix is effective or that my
      feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in
      downstream modules

## Further comments

fix for [Issue](https://github.com/orchestracities/ngsi-timeseries-api/issues/514)

[cla]: https://raw.githubusercontent.com/orchestracities/ngsi-timeseries-api/master/individual-cla.pdf
    "Martel Open Source Software Individual Contributor License Agreement"
[contrib]: https://github.com/smartsdk/ngsi-timeseries-api/blob/master/CONTRIBUTING.md
    "Contributing to QuantumLeap"

### CODE REVIEW

**Comment by daminichopra** [comment]
Gentle Reminder!!

**Comment by c0c0n3** [comment]
@daminichopra thanks so much for working on this. I only have a couple of remarks.

There's a typo in the warning message, I think you meant to say: `"use id and type rather than entityId and entityType from version 0.9"`?

@chicco785 is this what you wanted or is #514 calling for something more sophisticated? e.g. only warn if the field is actually used in the query?

also, do the fields actually need to be renamed according to @tstorek's [comment](https://github.com/orchestracities/ngsi-timeseries-api/issues/514#issuecomment-905861849) to #514? If so we should change the warning message too...

**Comment by c0c0n3** [comment]
@daminichopra 

> There's a typo in the warning message, I think you meant to say: "use id and type rather than entityId and entityType from version 0.9"?

Please ignore my comment, I've just realised I'm talking rubbish. Your message actually gets logged to a file not returned to the client in the HTTP request as I thought, so the wording as you have it now is perfect.

@chicco785 does "users" in #514 also includes API "clients"---which may then be able to display a warning to a user? If so, do we need to return a warning in the HTTP response, e.g. add a warning JSON field w/ the message: "use id and type rather than entityId and entityType from version 0.9"? Overkill?

**Comment by chicco785** [comment]
> @daminichopra
> 
> > There's a typo in the warning message, I think you meant to say: "use id and type rather than entityId and entityType from version 0.9"?
> 
> Please ignore my comment, I've just realised I'm talking rubbish. Your message actually gets logged to a file not returned to the client in the HTTP request as I thought, so the wording as you have it now is perfect.
> 
> @chicco785 does "users" in #514 also includes API "clients"---which may then be able to display a warning to a user? If so, do we need to return a warning in the HTTP response, e.g. add a warning JSON field w/ the message: "use id and type rather than entityId and entityType from version 0.9"? Overkill?

that was the idea, i think it's gonna be easy after #498 is merged

**Comment by daminichopra** [comment]
Hi @c0c0n3 @chicco785 , Please let me know If any further modification is required in this PR... Otherwise if it looks good please close this PR.

**Comment by c0c0n3** [comment]
hi @daminichopra 

> any further modification is required in this PR

Yep, like @chicco785 said, ideally there'd be an "API message" too---i.e. an extra field in the HTTP response. But let's put this on hold until  #498 gets merged...

**Comment by daminichopra** [comment]
> hi @daminichopra
> 
> > any further modification is required in this PR
> 
> Yep, like @chicco785 said, ideally there'd be an "API message" too---i.e. an extra field in the HTTP response. But let's put this on hold until #498 gets merged...

Hi @chicco785 , Please merge and close this PR as PR#498 is merged now. Thank You

**Review by chicco785 — CHANGES_REQUESTED** [review]
the build is failing, so we cannot merge.
most probably this due to the fact that there is some dirty changes related to 'src/reporter/delete.py' remove the changes there and let's see.

**Comment by daminichopra** [comment]
This PR has some issues so added new [PR](https://github.com/orchestracities/ngsi-timeseries-api/pull/584) For fix of Issue 514

**Pull request closed without merging**
