### PR TITLE
Removed subscription API

### PR DESCRIPTION
**Pull request by pooja1pathak**
## Proposed changes

Removed subscription API support. Fix for issue #424 

## Types of changes

What types of changes does your code introduce to the project: _Put
an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing
      functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after
creating the PR. If you're unsure about any of them, don't hesitate to
ask. We're here to help! This is simply a reminder of what we are going
to look for before merging your code._

- [x] I have read the [CONTRIBUTING][contrib] doc
- [ ] I have signed the [CLA][cla]
- [x] I have added tests that prove my fix is effective or that my
      feature works
- [x] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in
      downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion
by explaining why you chose the solution you did and what alternatives
you considered, etc...

[cla]: https://raw.githubusercontent.com/orchestracities/ngsi-timeseries-api/master/individual-cla.pdf
    "Martel Open Source Software Individual Contributor License Agreement"
[contrib]: https://github.com/smartsdk/ngsi-timeseries-api/blob/master/CONTRIBUTING.md
    "Contributing to QuantumLeap"

### CODE REVIEW

**Comment by chicco785** [comment]
hi @pooja1pathak looks like there are some bombing:

- this is about markdown formatting:
   https://github.com/orchestracities/ngsi-timeseries-api/pull/493/checks?check_run_id=2757917641#step:4:6

- this is about cleaning up removed packages from tests:
https://app.circleci.com/pipelines/github/orchestracities/ngsi-timeseries-api/205/workflows/59a54387-797e-4681-b5b7-c8631fa0d74c/jobs/598

- the other two errors are related to some coveralls issue, don't bother for now i will look into that

**Comment by pooja1pathak** [comment]
@chicco785 I have updated the failing test cases. Now the remaining issue is in coveralls.io. 

Kindy let me know if any further change is required from my side.

**Comment by chicco785** [comment]
thx!

the md linter reports this:

`docs/manuals/admin/check.md:32:81 MD013/line-length Line length [Expected: 80; Actual: 181]`

for the rest, I will check why you have this error with coveralls and see what can be done

**Comment by chicco785** [comment]
hopefully #494 solve the coveralls issue. if the build goes fine there, I will ask @c0c0n3 to approve, and once merged, you can rebase on the master to see if the testing cycle goes fine

**Comment by pooja1pathak** [comment]
Hi @chicco785 @c0c0n3 PR #494 is merged now. Please re-run the tests.

**Comment by chicco785** [comment]
the upload on coveralls is not working (no clue why it's not working...), but test are passing correctly, so this is good to me merged.

anyhow, given that the deprecation was announced for version 0.9 i would wait till we decide to move up to version 0.9. @c0c0n3 ?

**Comment by c0c0n3** [comment]
> given that the deprecation was announced for version 0.9 i would wait till we decide to move up to version 0.9

it makes sense, but we could merge this after `0.8.2` to avoid this code getting stale and @pooja1pathak having to maintain it for a while. My assumption is that the next release after `0.8.2` could be `0.9` maybe towards the end of the year, but I could be wrong!

**Comment by pooja1pathak** [comment]
@c0c0n3 @chicco785 I would like to know by when next release is planned.

**Comment by chicco785** [comment]
> @c0c0n3 @chicco785 I would like to know by when next release is planned.

I think we can target september, if we manage to progress with open PRs

**Comment by chicco785** [comment]
@c0c0n3 made a major refactor of the tests to wait for data consolidation in crate. can you rebase your pr?

**Comment by pooja1pathak** [comment]
@chicco785 I have rebased the code and updated the RELEASE_NOTES.md

**Review by chicco785 — APPROVED** [review]
LGTM

**Pull request merged**
