### PR TITLE
Update Adopters section

### PR DESCRIPTION
**Pull request by c0c0n3**
## Proposed changes

Reword adopters section, fix EKZ broken image link, and add link to profirator site.

## Types of changes

What types of changes does your code introduce to the project: 

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x] I have read the [CONTRIBUTING][contrib] doc
- [x] I have signed the [CLA][cla]
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [x] Any dependent changes have been merged and published in downstream modules

## Further comments

N/A

[cla]: https://fiware.github.io/contribution-requirements/individual-cla.pdf
    "FIWARE Individual Contributor License Agreement"
[contrib]: https://github.com/smartsdk/ngsi-timeseries-api/blob/master/CONTRIBUTING.md
    "Contributing to QuantumLeap"

### CODE REVIEW

**Comment by c0c0n3** [comment]
@ilarimikkonen I've added a link to your site but I don't have your company logo, this is what the updated adopters section looks like

- https://github.com/orchestracities/ngsi-timeseries-api/tree/adopters#adopters

if you don't have a logo I could use, we could just put a plain link in there. Let me know what you'd like me to do :-)

**Comment by c0c0n3** [comment]
@ilarimikkonen I've added the logo thanks. if you could just have a look at the result and give me the green light for the merge:

https://github.com/orchestracities/ngsi-timeseries-api/tree/adopters#adopters

thx!

**Review by ilarimikkonen — CHANGES_REQUESTED** [review]
@c0c0n3 logo looks bit fuzzy on my screen. Can we do something about that?

**Comment by c0c0n3** [comment]
@ilarimikkonen is it any better now?

**Review by ilarimikkonen — APPROVED** [review]
yes, thanks @c0c0n3

**Comment by c0c0n3** [comment]
@ilarimikkonen pleasure! should I go ahead and merge this PR?

**Review by ilarimikkonen — APPROVED** [review]
yes, please merge @c0c0n3

**Pull request merged**
