### PR TITLE
Remove duplicate code mentioned at:ngsi-timeseries-api/src/reporter/tests/test_timescale_types.py

### PR DESCRIPTION
**Pull request by NEC-Vishal**
## Proposed changes

remove the duplicate code in src/reporter/tests/test_timescale_types.py

## Types of changes

What types of changes does your code introduce to the project?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Maintenance (update of libraries or other dependences)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [X] I have read the [CONTRIBUTING][contrib] doc
- [X] I have signed the [CLA][cla]
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] I have run **all** the existing tests locally (not just those related to my feature) and there are no errors
- [X] After the last push to the PR branch, I have run the lint script locally and there are no changes to the code base
- [X] I have updated the [RELEASE NOTES][release]
- [X] I have added necessary documentation (if appropriate)
- [X] Any dependent changes have been merged and published in downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

[cla]: https://raw.githubusercontent.com/orchestracities/ngsi-timeseries-api/master/individual_cla.pdf
    "Martel Open Source Software Individual Contributor License Agreement"
[contrib]: https://github.com/orchestracities/ngsi-timeseries-api/blob/master/CONTRIBUTING.md
    "Contributing to QuantumLeap"
[release]: https://github.com/orchestracities/ngsi-timeseries-api/blob/master/RELEASE_NOTES.md
    "QuantumLeap Release Notes"

### CODE REVIEW

**Comment by NEC-Vishal** [comment]
Hi @chicco785 @c0c0n3 
I have raised a PR (pr655) for issue 655 , which removes the duplicity in the code , Please check the workflow.
Thanks

**Comment by NEC-Vishal** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by NEC-Vishal** [comment]
> @NEC-Vishal so it looks like we've got a couple of issues
> 
> * Markdown linter is moaning about extra whitespace: `RELEASE_NOTES.md:21 MD012/no-multiple-blanks Multiple consecutive blank lines [Expected: 1; Actual: 2]`
> * Your original code changes went missing? The only thing showing as a change in this PR is a line in the release notes?
> 
> Please help! :-)

hi @c0c0n3 sorry for this mistake at my end while raising PR.

I have updated the PR now, 
 Please check!

**Comment by NEC-Vishal** [comment]
Hi @c0c0n3 @chicco785 
can you Please review the updated PR for issue #655 .

**Comment by c0c0n3** [comment]
@NEC-Vishal good stuff, thanks so much.

There's still one snag. Like in #653, the GitHub code linter action is blocking this PR from being merged b/c autopep8 sniffed out something.  Can you please try running the linter locally and fixing whatever autopep is moaning about, then commit the fixes.

**Comment by NEC-Vishal** [comment]
Hi @c0c0n3 
Like in #653 
can we also merge this PR also as all test cases are passed except linter?

**Comment by c0c0n3** [comment]
@NEC-Vishal yea, same problem as in #653. no clue what the cause is, but clearly not an issue w/ your code. So I'm merging this PR. Thank you sooo much for your contrib!

**Pull request merged**
