### PR TITLE
Updated Response Models: fix for issue #476

### PR DESCRIPTION
**Pull request by pooja1pathak**
## Proposed changes

Updated Response Models as discussed in #476 

## Types of changes

What types of changes does your code introduce to the project: _Put
an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing
      functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after
creating the PR. If you're unsure about any of them, don't hesitate to
ask. We're here to help! This is simply a reminder of what we are going
to look for before merging your code._

- [x] I have read the [CONTRIBUTING][contrib] doc
- [x] I have signed the [CLA][cla]
- [x] I have added tests that prove my fix is effective or that my
      feature works
- [x] I have added necessary documentation (if appropriate)
- [x] Any dependent changes have been merged and published in
      downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion
by explaining why you chose the solution you did and what alternatives
you considered, etc...

[cla]: https://raw.githubusercontent.com/orchestracities/ngsi-timeseries-api/master/individual-cla.pdf
    "Martel Open Source Software Individual Contributor License Agreement"
[contrib]: https://github.com/smartsdk/ngsi-timeseries-api/blob/master/CONTRIBUTING.md
    "Contributing to QuantumLeap"

### CODE REVIEW

**Comment by pooja1pathak** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by pooja1pathak** [comment]
Hi @chicco785 @c0c0n3 , I signed the CLA but still it is failing in CLA.
There is an error in fetching repository in Code Linter/build. Please guide me how to resolve this error.

**Comment by chicco785** [comment]
hi @pooja1pathak i see that cla is signed... i will try to understand what's wrong. probably re-starting the check will solve it

**Comment by chicco785** [comment]
@pooja1pathak green light on cla :) now about the code linter, i think the issue is related to the fact that the linter tries to get the branch from our repo and not yours... I have to understand how to fix the issue ...

**Comment by chicco785** [comment]
i think there was some issue in the docker hub repo.

can you rebase and push?

`git rebase -i master`
`git push --force`

**Comment by pooja1pathak** [comment]
Hi @chicco785 I have reverted the changes which I have done to fix failing test cases. No test case is failing because of my changes. 

Kindly let me know if any further change is required from my side.

**Comment by pooja1pathak** [comment]
Hi @chicco785 @c0c0n3 please review my PR and merge if no further changes is required.

**Comment by chicco785** [comment]
@c0c0n3 @pooja1pathak 

some thinking is required here, we took the road to uniform with existing quantumleap formatting, i.e.
using `entityId` and `entityType`, but in ngsi v2, the correct naming would `id` and `type`.

so while complying with ngsi v2 is more correct, this may break existing clients... my proposal is to keep for now `entityId` and `entityType` and when moving to 0.9 change naming to comply better with ngsi v2.

thoughts?

**Comment by pooja1pathak** [comment]
Hi @chicco785 

I agree with you and in my comment https://github.com/orchestracities/ngsi-timeseries-api/issues/476#issuecomment-843743475 I have suggested the same.  In comment https://github.com/orchestracities/ngsi-timeseries-api/issues/476#issuecomment-843857047 you have suggested to use ```entityId``` and ```entityType```.

I agree with you, we can keep this naming as of now and can raise a new issue to comply with ngsi v2 and merge that change in 0.9 release.

**Comment by chicco785** [comment]
> Hi @chicco785
> 
> I agree with you and in my comment [#476 (comment)](https://github.com/orchestracities/ngsi-timeseries-api/issues/476#issuecomment-843743475) I have suggested the same. In comment [#476 (comment)](https://github.com/orchestracities/ngsi-timeseries-api/issues/476#issuecomment-843857047) you have suggested to use `entityId` and `entityType`.
> 
> > so while complying with ngsi v2 is more correct, this may break existing clients... my proposal is to keep for now entityId and entityType and when moving to 0.9 change naming to comply better with ngsi v2.
> 
> I agree with you, we can keep this naming as of now and can raise a new issue to comply with ngsi v2 and merge that change in 0.9 release.

fine with me. @c0c0n3 ?

**Comment by c0c0n3** [comment]
agreed, it seems to be the best option to me too

**Pull request merged**
